# Generated by Django 2.2.5 on 2019-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190908_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_attending',
        ),
        migrations.AddField(
            model_name='attendance',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
    ]
