# Generated by Django 2.2.5 on 2019-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190908_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seats_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='seats_booked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
