# Generated by Django 2.2.5 on 2019-09-10 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_connections_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='connections',
            new_name='Connection',
        ),
    ]
