# Generated by Django 2.2.5 on 2019-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190911_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='seats_booked',
            field=models.PositiveIntegerField(),
        ),
    ]
