# Generated by Django 2.2.5 on 2019-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190911_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
